### PR TITLE
Migrate from qc::try to ::try

### PR DESCRIPTION
**Pull request by PeterChaplin**

### CODE REVIEW

**Comment by bvw** [comment]
Thanks. Do you have a PgTcl do run local db tests ?

**Comment by PeterChaplin** [comment]
No

**Comment by bvw** [comment]
Could you see if you could do that using apt-get etc.
Also testing of success and failure cases to test each branch of the `::try`

**Comment by PeterChaplin** [comment]
local make test runs without errors or failures.

**Comment by bvw** [comment]
If you provoke failures do they generate and bubble as expected ?

**Comment by PeterChaplin** [comment]
I used the following:
```
proc /test.html {} {
    db_select_table {not a query}
}
```
and received a software bug as expected. I couldn't get the same error to work in the tcl test files.

**Pull request merged**
