### PR TITLE
Form2vars fix

### PR DESCRIPTION
**Pull request by nicky-johnstone**
Tcl
----
- [x] Are there comments throughout the code ?
- [x] Is each proc unit testable ?
- [x] Are variable names well chosen ?
- [x] Security: Is user input sanitised ?
- [x] Security: Is substitution protected from injection attacks ?
- [x] List what testing has been done.
  - `qc::args2vars [list foo hello bar.baz world <testing> test]`
  - `qc::dict2vars [dict create foo hello bar.baz world <testing> test]`
  - `qc::dict2vars [dict create foo hello bar.baz world <testing> test] foo bar.baz <testing>`

### CODE REVIEW

**Comment by nicky-johnstone** [comment]
Updated.

Do we want to add this check into `qc::args` and `qc::args2dict` too?

**Comment by daniel-qcode** [comment]
They should not be used to set namespaced variables so I suppose so

On 29 April 2016 at 09:37, Nicky Johnstone <notifications@github.com> wrote:

> Updated.
>
> Do we want to add this check into qc::args and qc::args2dict too?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/qcode-software/qcode-tcl/pull/365#issuecomment-215659138>
>



-- 
Kind Regards,
Daniel Clark
Qcode Software Limited
www.qcode.co.uk
Tel: +44(0) 1463 896 482

**Comment by bvw** [comment]
Could we centralise this restriction within qc::upset ?
The initial motivation for this was to stop setting variables outside the namespace intended.

**Comment by nicky-johnstone** [comment]
@bvw We can. Would we still want to check in `qc::form_var_names`, `qc::form_var_get`, and `qc::form_var_exists`?

**Comment by bvw** [comment]
Can you think of any issues with `qc::form_var_get "::some_variable"` that would be insecure or unexpected ?

**Comment by nicky-johnstone** [comment]
No. However a developer could circumvent `qc::form2vars` with:

```tcl
foreach name [qc::form_var_names] {
    set $name [qc::form_var_get $name]
}
```

Not sure whether we'd want to worry about that though.

**Comment by bvw** [comment]
I think we can put that one on the developer not the library.

**Comment by nicky-johnstone** [comment]
@daniel-qcode Updated

**Pull request merged**
