### PR TITLE
Add autocrop option to image handler

### PR DESCRIPTION
**Pull request by PeterChaplin**

### CODE REVIEW

**Comment by bvw** [comment]
Looks good. Could you add a checklist please.

**Comment by PeterChaplin** [comment]
Tcl
----
- [ ] Does each proc have a #| comment to describe what it does ?
- [ ] Are there comments throughout the code ?
- [ ] Is each proc unit testable ?
- [ ] Are the proc names well chosen ?
- [ ] Are variable names well chosen ?
- [ ] Security: Is user input sanitised ?
- [ ] Security: Is substitution protected from injection attacks ?
- [ ] List what testing has been done.
- [ ] UI changes - code reviewer should see changes.

**Comment by PeterChaplin** [comment]
Testing
----
- View a product on www DEV with excess whitespace border
- Delete cached image for that image
- Refresh page
- Check that displayed image is autocropped, and is of the correct dimensions.

**Comment by PeterChaplin** [comment]
Tested with https://github.com/qcode-software/mla-static/pull/24

**Pull request merged**
