### PR TITLE
Unit tests for AWS procs & IMDSv2

### PR DESCRIPTION
**Pull request by davidqc**
Tests avoiding the httpbin timeouts
```
Tests running in interp:  /usr/bin/tclsh
Tests located in:  /home/david/qcode-tcl/test
Tests running in:  /home/david/qcode-tcl
Temporary files stored in /home/david/qcode-tcl
Test files run in separate interpreters
Running tests that match:  *
Skipping test files that match:  l.*.test
Only running test files that match:  *.test
Tests began at Fri Apr 28 16:54:47 BST 2023
_s3.test
args.test
auth.test
aws.test
aws_s3_ls.test
aws_s3_rest_api.test
aws_s3_s3_uri_parse.test
aws_s3_xml.test
binary_convert.test
cast.test
castable.test
check.test
conn.test
conn_host.test
conn_location.test
conn_port.test
conn_protocol.test
conn_remote_ip.test
cookie.test
crypt.test
css_selector2xpath.test
csv.test
date.test
db.test
db_file.test
writing /tmp/HkCKJcoEog ...
written
Timeout set at 60 seconds
writing /tmp/roFA2mSyFw ...
written
Timeout set at 60 seconds
writing /tmp/r4zolyh9rs ...
written
db_introspection.test
db_trans.test
dict.test
dict_intersect.test
dict_is_subset.test
dicts_diff_any.test
email.test
file.test
writing /tmp/j9D2reXY5V ...
written
writing /tmp/je3HnRQf6u ...
written
form_layout.test
format.test
format_date.test
format_timestamp.test
html.test
html_options.test
html_table.test
html_table_doc.test
html_table_scroll.test
http.test
Docker installed...
Image kennethreitz/httpbin:latest present...
httpbin not running - starting...
Shutting down httpbin...
image_cache.test
image_file.test
image_resize_task.test
is.test
ldict.test
ldicts_diff_any.test
ll.test
math.test
mime.test
multimap.test
my.test
password.test
perl.test
perm.test
pgpass.test
response.test
response_login.test
response_redirect.test
return_next.test
s3.test
writing /tmp/FNaXb8S0dv ...
written
writing /tmp/NQsc3Azm5t ...
written
writing /tmp/ZEhMWywStk ...
written
writing /tmp/28ews3XA8k ...
written
writing /tmp/aNXFTmgYMY ...
written
writing /tmp/vfzgRge1Ze ...
written
Timeout set at 60 seconds
writing /tmp/C326UOIlhR ...
written
Timeout set at 60 seconds
writing /tmp/wKLEM0G2nq ...
written
writing /tmp/dxOfnDNnKi ...
written
writing /tmp/73TqRAiEht ...
written
writing /tmp/j7wXB4kx6g ...
written
writing /tmp/f7nrcnu1iP ...
written
writing /tmp/EUVhKUsNaE ...
written
Upload init for s3_tools_test-upload-1.0-test to qcodetcl-tcltest-s3.
Upload_id: uJqi7HlD73c0SYwDpT5brUaMszrcmMRHZ0NbLjMVVnWUnZEbLhxBdQVzm86S2XZqf77T8CNPAwHV1POgfmf06kvRLGhU7.U0iOwLPa0JiOmtgGLgKFHuz1_C2ocGo3ImHoxmVyFlNd1v_OgSbpv6FA--
Timeout set as 10000 ms
Uploading /tmp/EUVhKUsNaE: Sending part 1 of 1
Completing Upload to s3_tools_test-upload-1.0-test in qcodetcl-tcltest-s3.
writing /tmp/5IGPpZqhok ...
written
Upload init for s3_tools_test-upload-1.0-test to qcodetcl-tcltest-s3.
Upload_id: aI4AVelDWY_W2oGM1c36.ur0vw0I1OOgO1koRJQCD4PxvYCS3PYWU9QMsyK43xdnZrvJb7J12Vn9hUXaf_NuE0IGkLAPyS4_kAgMAtB26oTzrfcmN7S8IB6Se_rhSrmIeOf2KsNvOV7mo5X2JlIv_Q--
Timeout set as 10000 ms
Uploading /tmp/5IGPpZqhok: Sending part 1 of 1
Completing Upload to s3_tools_test-upload-1.0-test in qcodetcl-tcltest-s3.
writing /tmp/YnKXNfSovg ...
written
Upload init for s3_tools_test-upload-1.2-test to qcodetcl-tcltest-s3.
Upload_id: 9nqe2LVr6bbQZaL5ZVlW81cD1XZyUQKlZuUN9_0Mc4zHrJpTKgvTqVKHn5yNGJfewsxu5tdYY9hOcFdten4ZsNaFUjRQI0onewvX2_iIMtrLAxNyHwjejGvghZn9R0fAES0_ZIxbIaH6OL5._CgnzQ--
writing /tmp/juhnA4xFaC ...
written
Upload init for s3_tools_test-upload-1.3-test to qcodetcl-tcltest-s3.
Upload_id: KbZT4yfeNPKwAoW9r6jgNIgrEfnP_ucdrTzdBS5O.PvNRdQ.4RYM8uT8a.NXDWgAdCHFvhGl1vHfAOBHimnrx_Ah1qKksdYImnCRnhfG9EpX07GQra5jiFBS2E9561Gl0tjMx2Bvj30U93BNyHEb7g--
writing /tmp/5DB6t8SPJW ...
written
Upload init for s3_tools_test-upload-1.4-test to qcodetcl-tcltest-s3.
Upload_id: MlFasf8UOoNXqpo2BxOD48VzN68L10bU7D1gFz_v.XWXBO0bKVzd4CyDR9pCeXApQ_bBJknPHsFhszYtP5QOj0AhOs0pzN6pSriPGPN1LZLi_S4wpPx6nPN2KsvSVIRRR_L4Uj.b0w9N2RKjfSsu0w--
writing /tmp/3MFwUx5cuh ...
written
Upload init for s3_tools_test-upload-1.5-test to qcodetcl-tcltest-s3.
Upload_id: PgxLGAM7CFj1nEqmGvx0CVgoSD0Px_GU12FEGusdwcqaDQ_wAhTa1NXf2G.Xj.gth4GdrLZuE9v132Mz_tyIyRbi93ZNO0n0OwNHyVzLsJyPsOANtHOHPRGTumTv1EC5VtBESwaVBxx60QApnXAioA--
Timeout set as 10000 ms
Uploading /tmp/3MFwUx5cuh: Sending part 1 of 1
writing /tmp/FwnFvrC3ZD ...
written
Upload init for s3_tools_test-upload-1.6-test to qcodetcl-tcltest-s3.
Upload_id: co4Xgw_yCAH9WiH6qAhLvOoy5VuECbD3YP064fXWwbx3oMsGcITn0o.S_bA0BQCGZ9AJRRX2MUDgsQHmUQ5qDrw60xOfy5uJcdzCG9mehJjR2EbDoRVGAl9mImtS4TFkcTw2_pdHXKtFyYHPESeelw--
writing /tmp/SR1rA8evNv ...
written
writing /tmp/YnJDSO3tAj ...
written
writing /tmp/uHVv2rkg6C ...
written
s3_uri.test
soap.test
sort.test
sql.test
sql_where.test
sql_where_in.test
style.test
table.test
tabular_text.test
tson.test
upset.test
url.test
user_agent.test
util.test
util_list.test
util_string.test
validate.test
widget.test
xml.test

Tests ended at Fri Apr 28 16:55:45 BST 2023
all.tcl:	Total	1870	Passed	1857	Skipped	13	Failed	0
Sourced 82 Test Files.
Number of tests skipped for each constraint:
	1	earlier_than_8.5
	12	knownBug


============================================


Summary of Test Results
	Total	1870	Passed	1857	Skipped	13	Failed	0

Sourced 82 Test Files.


============================================

```

### CODE REVIEW

**Comment by daniel-qcode** [comment]
can failing tests be fixed ... maybe try changing URL to Qcode website instead of httpbin

**Comment by davidqc** [comment]
> can failing tests be fixed ... maybe try changing URL to Qcode website instead of httpbin

They can be fixed - should probably be testing via emulation rather than making actual http calls. I hesitated to do it because it's not really part of this task - @RichardDanson happy for the additional time?

**Comment by RichardDanson** [comment]
@davidqc as we go we should ensure tcl tests / unit tests function, are there if none existed etc and so yes this should be included I think. When we try to estimate work we should consider the state of tests and effort required to bring them up to date.

How long would fixing the tests take?

**Comment by davidqc** [comment]
100% that we should always maintain clean unit tests - was just a query on the resource for doing this.
These tests are failing on master for me so will create a different PR for them...

**Comment by davidqc** [comment]
Tests now fixed from https://github.com/qcode-software/qcode-tcl/pull/742

**Review by daniel-qcode — APPROVED** [review]

**Pull request merged**
