### PR TITLE
JSON Response Extend

### PR DESCRIPTION
**Pull request by nicky-johnstone**
Extends the JSON Response to include a `status` element that indicates `valid` or `invalid`.

Checklist
----
- [x] Does each proc have a #| comment to describe what it does ?
- [x] Are there comments throughout the code ?
- [x] Is each proc unit testable ?
- [x] Are the proc names well chosen ?
- [x] Are variable names well chosen ?
- [x] List what testing has been done.
  - Unit testing `qc::status valid` and `qc::status invalid`.
  - Testing `qc::data2json` after setting the status and also without setting the status to test the default.

### CODE REVIEW

**Comment by nicky-johnstone** [comment]
One thing we may want to consider is automatically setting the status to `invalid` if a record item is set as invalid. Not sure if it's best to do this or leave it to the developer to take care of.

For example:

```tcl
qc::record invalid username $username "That username is already taken."
```

would automatically call

```tcl
qc::status invalid
```

**Comment by bvw** [comment]
Lets not create or rely on a functional dependency between the global status and the aggregate status of each field.
It may be conceivable for each of the 4 possible combinations to make sense at some point.

| All valid | Global Valid |
| --------- | -------------- |
| Yes | Yes |
| Yes | No |
| No | Yes |
| No | No |

**Comment by bvw** [comment]
`qc::status` seems like quite a special name but just floating ideas.
Should we consider names qualified by a namespace etc.

`qc::status invalid`
`qc::response::status invalid`
`qc::response_status invalid`

`qc::record invalid username $username "That username is already taken"`
`qc::response::record invalid username $username "That username is already taken"`
`qc::response_record invalid username $username "That username is already taken"`

**Comment by nicky-johnstone** [comment]
I've created the namespace `qc::response` and moved the API over to this namespace. I'd agree that it is more fitting and sensible to do so because it makes the intent of the call more obvious. Also easier to do now while the API is still young and not widely used.

The API is now called as such:

```
qc::response status x
qc::response record x
qc::response message x
qc::response action x
```

where `x` is a procedure of that particular ensemble.

**Comment by daniel-qcode** [comment]
@bvw looks good to me

**Pull request merged**
