### PR TITLE
3883 remittance parser errors

### PR DESCRIPTION
**Pull request by PeterChaplin**

### CODE REVIEW

**Comment by bvw** [comment]
Is there an S3 test suite ?

**Comment by PeterChaplin** [comment]
@bvw yes, we have a test suite

**Comment by bvw** [comment]
Can you paste in the results of the tests passing here and I can then merge.

**Comment by PeterChaplin** [comment]
Do you have an example of what the `~/.qcode-tcl` file should look like and which s3 test bucket I should be using?

**Comment by PeterChaplin** [comment]
image

**Pull request merged**
