### PR TITLE
Trim sql_sort args before quoting

### PR DESCRIPTION
**Pull request by PeterChaplin**

### CODE REVIEW

**Comment by daniel-qcode** [comment]
What issue does this fix?

**Comment by PeterChaplin** [comment]
Encountered problems on DEV:
https://github.com/qcode-software/mla-erp/issues/1822
I don't think the sql_injection work has been rolled out to LIVE yet, so it's not currently operational.
The existing sql_sort code does make an effort to support comma-separated arguments, though,

**Comment by PeterChaplin** [comment]
Test case added

**Comment by daniel-qcode** [comment]
@PeterChaplin Have you tested the case where the identifier has a alias eg `sql_order p.product_code`?

If this doesn't work then please raise GitHub issue to address.

**Comment by PeterChaplin** [comment]
Issue raised: https://github.com/qcode-software/qcode-tcl/issues/407

**Pull request merged**
