### PR TITLE
Add -not option to db_row_exists, and add sql_where_not proc

### PR DESCRIPTION
**Pull request by PeterChaplin**

### CODE REVIEW

**Comment by PeterChaplin** [comment]
For example:
```tcl
# Validating input for product update
if { [db_row_exists -not {~ product_id} product ~ product_code] } {
  error "Another product has code $product_code" {} USER
}
```

**Comment by PeterChaplin** [comment]
Updated with tests (passed on DEV)

**Comment by nicky-johnstone** [comment]
What would the benefits of the `-not` flag be versus something like:


```tcl
if { ! [db_row_exists product ~ product_id product_code]
       && [db_row_exists product ~ product_code] } {
    ...
}
```

The only benefit that I can think of is that it compacts it down to one line and one query instead of two. Is that enough of an advantage to warrant the addition of the `-not` flag?

**Comment by PeterChaplin** [comment]
For checking uniqueness constraints, I don't think there are any other differences.

I can imagine other situations where we might want to use a `-not` flag, but I can't recall any of them actually occurring, so it might be better to leave this for now.

**Comment by daniel-qcode** [comment]
Unnecessary for now ... closing

**Pull request closed without merging**
